variable "environment" {
  type        = string
  description = "Environment name (prod/dev)"
  default     = "dev"
}

variable "route53_zone_id" {
  type        = string
  description = "Zone ID for PointrApp in R53"
  default     = "Z021125431208XT5W7T05"
}

variable "dns_target" {
  type        = string
  description = "DNS target generated by custom domain attachment"
  default = "none"
}

variable "certificate_validation_records" {
  type        = list(string)
  description = "Records to validate in Route 53"
  default     = ["none"]
}