variable "environment" {
  type        = string
  description = "Environment name (prod/dev)"
  default     = "dev"
}

variable "route53_zone_id" {
  type        = string
  description = "Zone ID for PointrApp in R53"
  default     = "Z021125431208XT5W7T05"
}

variable "dns_target" {
  type        = string
  description = "DNS target generated by custom domain attachment"
  default = "none"
}

variable "certificate_validation_records" {
  description = "Certificate validation records returned from App Runner"
  type = list(object({
    name  = string
    type  = string
    value = string
  }))
  default = []
}