variable "project_name" {
  type        = string
  description = "Name of this project"
  default     = "PointrApp"
}

variable "environment" {
  type        = string
  description = "Environment name (prod/dev)"
  default     = "dev"
}

variable "image_uri" {
  type        = string
  description = "ECR image URI to deploy"
  default     = "placeholder"
}

variable "route53_zone_id" {
  type        = string
  description = "Zone ID for pointrapp in R53"
  default     = "Z021125431208XT5W7T05"
}

variable "dns_target" {
  type        = string
  description = "DNS target generated by custom domain attachment"
  default = "none"
}

variable "certificate_validation_records" {
  description = "Certificate validation records returned from App Runner"
  type = list(object({
    name  = string
    type  = string
    value = string
  }))
  default = []
}

variable "cdn_domain_avatars" {
  type        = string
  description = "CDN domain for avatar hosting"
  default     = "cdn.pointrapp.com"
}