variable "project_name" {
  type = string
  description = "Identifier for the project."
}

variable "environment" {
  type        = string
  description = "Environment name (prod/dev)"
  default     = "dev"
}

variable "image_uri" {
  type        = string
  description = "ECR image URI to deploy"
}

variable "stage" {
  type        = string
  description = "Stage for the WebSocket APIs"
  default     = "dev"
}

variable "lambda_runtime" {
  type        = string
  description = "Version of lambda"
  default     = "nodejs20.x"
}

variable "dns_target" {
  type        = string
  description = "DNS target generated by custom domain attachment"
  default = "none"
}